\copy users(fname,lname,email,password, photo_url) FROM '/root/chairbnBeyond/database/csv/test_users.csv' DELIMITER ',' CSV HEADER;
\copy reviews(listingId, userId, review, rating, cleanliness, communication, checkin, accuracy, location, value, bookingId) FROM '/root/chairbnBeyond/database/csv/test_reviews.csv' DELIMITER ',' CSV HEADER;
\copy locations(latitude, longitude, city) FROM '/root/chairbnBeyond/database/csv/test_locs.csv' DELIMITER ',' CSV HEADER;
\copy listings(title, description, price, locationid, hostId) FROM '/root/chairbnBeyond/database/csv/test_listings.csv' DELIMITER ',' CSV HEADER;
\copy listing_photos(listingId, photo_url) FROM '/root/chairbnBeyond/database/csv/test_listing_photos.csv' DELIMITER ',' CSV HEADER;
\copy listing_amenities(listingid, amenityid ) FROM '/root/chairbnBeyond/database/csv/test_listing_amenities.csv' DELIMITER ',' CSV HEADER;
\copy hosts(userId, about) FROM '/root/chairbnBeyond/database/csv/test_hosts.csv' DELIMITER ',' CSV HEADER;
\copy bookings(listingId, userId, startDate, endDate, numGuests) FROM '/root/chairbnBeyond/database/csv/test_bookings.csv' DELIMITER ',' CSV HEADER;
\copy amenity_types(amenity_type) FROM '/root/chairbnBeyond/database/csv/test_amenity_types.csv' DELIMITER ',' CSV HEADER;
\copy amenities(amenity, typeId) FROM '/root/chairbnBeyond/database/csv/test_amenities.csv' DELIMITER ',' CSV HEADER;